apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 977932533773.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 977932533773.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: 4462cf9f
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
